apiVersion: v1
kind: Service
metadata:
    name: conductor-service
    namespace: conductor
spec:
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080 
        name: rest-api     
      - protocol: TCP
        port: 3000
        targetPort: 3000        
        name: conductor-api
  selector:
      name: conductor-server
  type: LoadBalancer